<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Olivia Lombardo">
<meta name="dcterms.date" content="2025-12-02">

<title>Neighborhood Crime Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="neighborhood-crime-analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="neighborhood-crime-analysis_files/libs/quarto-html/quarto.js"></script>
<script src="neighborhood-crime-analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="neighborhood-crime-analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="neighborhood-crime-analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="neighborhood-crime-analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="neighborhood-crime-analysis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="neighborhood-crime-analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="neighborhood-crime-analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="neighborhood-crime-analysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Neighborhood Crime Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Olivia Lombardo </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 2, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="description-of-the-data" class="level2">
<h2 class="anchored" data-anchor-id="description-of-the-data">Description of the data</h2>
<p>These data describe 343 neighborhoods in a major city observed over a 10 year period. It contains the following measures:</p>
<ul>
<li><p><code>robbery</code>: A count of the number of robberies occurring in the neighborhood within the 10 year study period. Units are individual robbery incidents.</p></li>
<li><p><code>disadvantage</code>: An index of concentrated disadvantage (e.g., unemployment, poverty). Units are standard deviations and higher values indicate higher disadvantage. e.g., a neighborhood with disadvantage equal to 1 is 1 standard deviation higher in disadvantage than a neighborhood with disadvantage equal to 0.</p></li>
<li><p><code>instability</code>: An index of residential instability (e.g., home ownership, recent moves). Units are standard deviations and higher values indicate higher instability.</p></li>
<li><p><code>heterogeneity</code>: An index of ethnic heterogeneity (e.g., percent foreign-born, ethnic diversity). Units are standard deviations and higher values indicate higher heterogeneity</p></li>
<li><p><code>control</code>: An index of informal social control capacity. Units are standard deviations and higher values indicate higher social control.</p></li>
<li><p><code>opportunity</code>: A three-level ordinal variable capturing the density of features of the built environment that provide criminal opportunities (e.g., abandoned buildings, street lighting, commercial destinations).</p></li>
</ul>
</section>
<section id="fundamentals" class="level1">
<h1>Fundamentals</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.3     ✔ tibble    3.2.1
✔ purrr     1.0.2     ✔ tidyr     1.3.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(flextable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'flextable'

The following object is masked from 'package:purrr':

    compose</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>neighb_crime <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://clanfear.github.io/ioc_iqa/_data/neighb_crime.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 343 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): opportunity
dbl (5): disadvantage, instability, heterogeneity, control, robbery

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(neighb_crime)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "disadvantage"  "instability"   "heterogeneity" "control"      
[5] "opportunity"   "robbery"      </code></pre>
</div>
</div>
<section id="correlation" class="level2">
<h2 class="anchored" data-anchor-id="correlation">Correlation</h2>
<blockquote class="blockquote">
<p>Calculate the correlation between <code>robbery</code> and <code>control</code>, then calculate the correlation between <code>robbery</code> and <code>disadvantage</code>. In a single sentence of plain language, explain what these values mean.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation, robbery and control</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(neighb_crime<span class="sc">$</span>robbery, neighb_crime<span class="sc">$</span>control)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.5761815</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation, robbery and disadvantage</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(neighb_crime<span class="sc">$</span>robbery, neighb_crime<span class="sc">$</span>disadvantage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.441253</code></pre>
</div>
</div>
<p><strong>Answer:</strong> Neighborhoods with higher levels of informal social control tend to have fewer robberies (correlation is -0.58). Neighborhoods with higher levels of disadvantage tend to have more robberies (correlation is 0.44).</p>
</section>
<section id="linear-model" class="level2">
<h2 class="anchored" data-anchor-id="linear-model">Linear Model</h2>
<section id="estimates" class="level3">
<h3 class="anchored" data-anchor-id="estimates">Estimates</h3>
<blockquote class="blockquote">
<p>Estimate a linear model where <code>robbery</code> is predicted by <code>control</code>, <code>opportunity</code>, <code>disadvantage</code>, <code>instability</code>, and <code>heterogeneity</code>. Show the summary output here too—you’ll want it for the next question.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run a linear model where robbery is predicted by control, opportunity, disadvantage, instability, and heterogeneity</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(robbery <span class="sc">~</span> control <span class="sc">+</span> opportunity <span class="sc">+</span> disadvantage <span class="sc">+</span> instability <span class="sc">+</span> heterogeneity,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> neighb_crime) <span class="sc">|&gt;</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept)           control    opportunitylow opportunitymedium 
        34.408614         -6.834480        -23.141621        -20.099348 
     disadvantage       instability     heterogeneity 
         1.548065         -0.862183          1.212982 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>neigh_crime_lm <span class="ot">&lt;-</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(robbery <span class="sc">~</span> control <span class="sc">+</span> opportunity <span class="sc">+</span> disadvantage <span class="sc">+</span> instability <span class="sc">+</span> heterogeneity,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> neighb_crime)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  neigh_crime_lm <span class="sc">|&gt;</span> <span class="fu">coef</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept)           control    opportunitylow opportunitymedium 
        34.408614         -6.834480        -23.141621        -20.099348 
     disadvantage       instability     heterogeneity 
         1.548065         -0.862183          1.212982 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(neigh_crime_lm)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    Estimate Std. Error    t value     Pr(&gt;|t|)
(Intercept)        34.408614  1.5839193  21.723716 5.513367e-66
control            -6.834480  0.7488013  -9.127227 6.669077e-18
opportunitylow    -23.141621  2.0657574 -11.202487 5.789890e-25
opportunitymedium -20.099348  1.8504666 -10.861773 9.345673e-24
disadvantage        1.548065  0.7890134   1.962026 5.058457e-02
instability        -0.862183  0.7027278  -1.226909 2.207158e-01
heterogeneity       1.212982  0.6841558   1.772962 7.714092e-02</code></pre>
</div>
</div>
</section>
<section id="equation" class="level3">
<h3 class="anchored" data-anchor-id="equation">Equation</h3>
<blockquote class="blockquote">
<p>Write out the full regression equation from this model (e.g., <span class="math inline">\(y = 2 + 3.5*x\)</span>). For brevity, you can round the coefficients to 2 decimal places and abbreviate words, as long as it is still clear.</p>
</blockquote>
<p><span class="math display">\[
\hat{y} = 34.41 - (6.83 * control) - (23.14 * opportunityLow) - (20.10 * opportunityMedium) + (1.55 * disadvantage) - (0.86 * instability) + (1.21 * heterogeneity)
\]</span></p>
</section>
<section id="prediction" class="level3">
<h3 class="anchored" data-anchor-id="prediction">Prediction</h3>
<blockquote class="blockquote">
<p>Based on this model, how many robberies would we expect to see in a neighbourhood with “high” <code>opportunity</code>, <code>control</code> at -1, <code>disadvantage</code> at 1, and both <code>heterogeneity</code> and <code>instability</code> at 0.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicting robbery based on levels of opportunity, control, disadvantage, heterogeneity, and instability</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(neigh_crime_lm, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">opportunity =</span> <span class="st">"high"</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">control =</span> <span class="sc">-</span><span class="dv">1</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">disadvantage =</span> <span class="dv">1</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">heterogeneity =</span> <span class="dv">0</span>,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">instability =</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
42.79116 </code></pre>
</div>
</div>
<p><strong>Answer:</strong> I would expect to see 43 robberies in a neighbourhood with “high” <code>opportunity</code>, <code>control</code> at -1, <code>disadvantage</code> at 1, and both <code>heterogeneity</code> and <code>instability</code> at 0.</p>
</section>
<section id="r-squared" class="level3">
<h3 class="anchored" data-anchor-id="r-squared">R-squared</h3>
<blockquote class="blockquote">
<p>In 1 or 2 sentences, what is the <span class="math inline">\(R^2\)</span> value for this model and how would you interpret it?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#R-squared for the model</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(neigh_crime_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.572         0.565  11.9      74.9 5.32e-59     6 -1334. 2684. 2715.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p><strong>Answer:</strong> Around 57% of the variance in the number of robberies is explained by our model.</p>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<blockquote class="blockquote">
<p>In 1 or 2 sentences each, how would you interpret (1) the coefficient for <code>instability</code> and (2) the coefficient for “low” opportunity? Include their statistical significance in your interpretation.</p>
</blockquote>
<p><strong>Answer:</strong></p>
<p><strong>(1)</strong> For every one unit increase in instability there will be around 0.86 fewer robberies, holding all else constant, but the effect is not significant (p = 0.22).</p>
<p><strong>(2)</strong> Neighborhoods with low opportunity will have around 23 fewer robberies than high opportunity neighborhoods, holding all else constant, and the effect is very statistically significant (p &lt;0.001).</p>
</section>
</section>
<section id="histograms" class="level2">
<h2 class="anchored" data-anchor-id="histograms">Histograms</h2>
<blockquote class="blockquote">
<p>Create a histogram or density plot of the <code>robbery</code> variable. What do you notice about this variable?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a historgram for robberies across neighborhoods, with robbery counts on the x-axis and neighborhoods on the y-axis</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(neighb_crime,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> robbery)) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">2.5</span>, <span class="at">fill =</span> <span class="st">"maroon"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Robberies Across Neighborhoods"</span>, <span class="at">x =</span> <span class="st">"Cases of Robbery"</span>, <span class="at">y =</span> <span class="st">"Neighborhoods"</span>) <span class="sc">+</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="neighborhood-crime-analysis_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong> Robbery is skewed to the right. Most neighborhoods have only a small number of robberies, while a smaller number of neighborhoods have a very large number of robberies.</p>
<blockquote class="blockquote">
<p>Next, repeat your histogram or density plot but use the <strong>log</strong> of the <code>robbery</code> variable. How does this compare to the prior plot?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a histogram using the log of the robbery variable</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>robbery_log <span class="ot">&lt;-</span> <span class="fu">log</span>(neighb_crime<span class="sc">$</span>robbery)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(neighb_crime,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> robbery_log)) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.4</span>, <span class="at">fill =</span> <span class="st">"maroon"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Log Robberies Across Neighborhoods"</span>, <span class="at">x =</span> <span class="st">"Log Cases of Robbery"</span>, <span class="at">y =</span> <span class="st">"Neighborhoods"</span>) <span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="neighborhood-crime-analysis_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong> This histogram looks closer to normal distribution.</p>
</section>
</section>
<section id="moderate-problems" class="level1">
<h1>Moderate Problems</h1>
<section id="dag-to-model" class="level2">
<h2 class="anchored" data-anchor-id="dag-to-model">DAG to model</h2>
<blockquote class="blockquote">
<p>Consider the DAG below that depicts a model of social disorganization theory with criminal opportunity added.</p>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="neighborhood-crime-analysis_files/figure-html/dag-1.png" style="width:50.0%;height:50.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Compare your linear model from question 1.2 to the DAG. Based on the statistical significance of the coefficients, do our model results agree with the theory in the DAG? That is, do we find evidence that all the paths on the DAG that lead into robbery exist? Why or why not?</p>
</blockquote>
<p><strong>Answer:</strong> Based on the statistical significance of the coefficients, it seems that the results from our model agrees with the theory in the DAG for control and opportunity since they are both statistically significant. Disadvantage is also supported but not as strongly. Instability and heterogeneity are not supported because their coefficients are not statistically significant.</p>
</section>
<section id="log-level-model" class="level2">
<h2 class="anchored" data-anchor-id="log-level-model">Log-level Model</h2>
<blockquote class="blockquote">
<p>We might consider using the <strong>log</strong> of <code>robbery</code> as our outcome instead. Rewrite the linear model from 1.2 to predict the log of <code>robbery</code> using the other covariates. Is it possible to use <code>anova()</code> to compare this new log-level model to the previous linear one?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run a linear model where the log of robbery is predicted by control, opportunity, disadvantage, instability, and heterogeneity</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(robbery_log <span class="sc">~</span> control <span class="sc">+</span> opportunity <span class="sc">+</span> disadvantage <span class="sc">+</span> instability <span class="sc">+</span> heterogeneity,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> neighb_crime) <span class="sc">|&gt;</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept)           control    opportunitylow opportunitymedium 
       3.14552352       -0.48264152       -1.12884073       -0.70362613 
     disadvantage       instability     heterogeneity 
       0.13151901       -0.02572597        0.02027276 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>neigh_crime_lm_log <span class="ot">&lt;-</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(robbery_log <span class="sc">~</span> control <span class="sc">+</span> opportunity <span class="sc">+</span> disadvantage <span class="sc">+</span> instability <span class="sc">+</span> heterogeneity,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> neighb_crime)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>neigh_crime_lm_log <span class="sc">|&gt;</span> <span class="fu">coef</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept)           control    opportunitylow opportunitymedium 
       3.14552352       -0.48264152       -1.12884073       -0.70362613 
     disadvantage       instability     heterogeneity 
       0.13151901       -0.02572597        0.02027276 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>neigh_crime_lm_log <span class="sc">|&gt;</span> <span class="fu">tidy</span>() <span class="sc">|&gt;</span> <span class="fu">select</span>(term, estimate, std.error, p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 4
  term              estimate std.error   p.value
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)         3.15      0.0617 3.43e-160
2 control            -0.483     0.0292 2.13e- 45
3 opportunitylow     -1.13      0.0805 1.65e- 35
4 opportunitymedium  -0.704     0.0721 5.60e- 20
5 disadvantage        0.132     0.0307 2.45e-  5
6 instability        -0.0257    0.0274 3.48e-  1
7 heterogeneity       0.0203    0.0267 4.47e-  1</code></pre>
</div>
</div>
<p><strong>Answer:</strong> We cannot use <code>anova()</code> to compare this new log-level model to the previous linear one because the new log-level model is not nested.</p>
</section>
<section id="quadratic-term" class="level2">
<h2 class="anchored" data-anchor-id="quadratic-term">Quadratic term</h2>
<blockquote class="blockquote">
<p>A substantial literature in community criminology suggests <code>disadvantage</code> has a non-linear effect on crime: Once disadvantage gets relatively high, further disadvantage doesn’t contribute much to crime. Add a <strong>quadratic polynomial</strong> functional form of <code>disadvantage</code> to your model from 2.2 (or 1.2 if you didn’t know how to do 2.2).</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run a linear model where the log of robbery is predicted by control, opportunity, disadvantage (in quadtratic polynomial functional form), instability, and heterogeneity</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>neigh_crime_lm_log2 <span class="ot">&lt;-</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(robbery_log <span class="sc">~</span> control <span class="sc">+</span> opportunity <span class="sc">+</span> disadvantage <span class="sc">+</span> <span class="fu">I</span>(disadvantage<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> instability <span class="sc">+</span> heterogeneity,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> neighb_crime)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>neigh_crime_lm_log2 <span class="sc">|&gt;</span> <span class="fu">coef</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept)           control    opportunitylow opportunitymedium 
       3.26098537       -0.46547082       -1.16319220       -0.76092079 
     disadvantage I(disadvantage^2)       instability     heterogeneity 
       0.12138922       -0.07898697       -0.01948948        0.02488793 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>neigh_crime_lm_log2 <span class="sc">|&gt;</span> <span class="fu">tidy</span>() <span class="sc">|&gt;</span> <span class="fu">select</span>(term, estimate, std.error, p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
  term              estimate std.error   p.value
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)         3.26      0.0649 4.07e-158
2 control            -0.465     0.0286 2.20e- 44
3 opportunitylow     -1.16      0.0785 1.42e- 38
4 opportunitymedium  -0.761     0.0711 3.31e- 23
5 disadvantage        0.121     0.0299 6.18e-  5
6 I(disadvantage^2)  -0.0790    0.0170 5.03e-  6
7 instability        -0.0195    0.0266 4.64e-  1
8 heterogeneity       0.0249    0.0259 3.37e-  1</code></pre>
</div>
</div>
</section>
<section id="model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="model-comparison">Model comparison</h2>
<blockquote class="blockquote">
<p>Evaluate whether there is statistical evidence that you should use the quadratic functional form of disadvantage instead of the linear term alone (i.e., does it fit better than it did before?).</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare models using ANOVA</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(neigh_crime_lm_log, neigh_crime_lm_log2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: robbery_log ~ control + opportunity + disadvantage + instability + 
    heterogeneity
Model 2: robbery_log ~ control + opportunity + disadvantage + I(disadvantage^2) + 
    instability + heterogeneity
  Res.Df    RSS Df Sum of Sq     F   Pr(&gt;F)    
1    336 72.806                                
2    335 68.411  1    4.3946 21.52 5.03e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Answer:</strong> There is statistical evidence that we should use the quadratic functional form of disadvantage instead of the linear term alone because the RSS (residual sum of squares) decreases (72.8 to 68.4) and the p value is very low and statistically significant (p &lt; 0.001).</p>
</section>
</section>
<section id="harder-problems" class="level1">
<h1>Harder Problems</h1>
<section id="interaction-plot" class="level2">
<h2 class="anchored" data-anchor-id="interaction-plot">Interaction plot</h2>
<blockquote class="blockquote">
<p>Create a scatterplot with <code>control</code> on the x-axis and the <strong>log</strong> of <code>robbery</code> on the y-axis. Include different coloured regression lines for each level of <code>opportunity</code>. In a sentence or two, what do you see in this plot?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatterplot</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(neighb_crime ,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x     =</span> control,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">y     =</span> robbery_log,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> opportunity)) <span class="sc">+</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="neighborhood-crime-analysis_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong> The results are interesting because control matters at all levels of opportunity, but because the slopes of the lines are different, control matters differently at different opportunity levels. For example, at a high opportunity are, since the slope is the most flat of the three opportunity levels, robberies would not be reduced as much is you were to increase control (compared to low or medium opportunity areas).</p>
</section>
<section id="interaction-model" class="level2">
<h2 class="anchored" data-anchor-id="interaction-model">Interaction Model</h2>
<blockquote class="blockquote">
<p>Based on the plots from 3.1, we might expect there is an <strong>interaction</strong> between <code>control</code> and <code>opportunity</code>. That is, we think the effect of <code>control</code> on <code>robbery</code> might be different at different levels of <code>opportunity</code>. Take your linear model from 2.3—with the logged outcome and quadratic disadvantage—and add an interaction between <code>control</code> and <code>opportunity</code>.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run a linear model where the log of robbery is predicted by the interaction between control and opportunity, disadvantage (in quadtratic polynomial functional form), instability, and heterogeneity</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>neigh_crime_lm_interaction <span class="ot">&lt;-</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(robbery_log <span class="sc">~</span> control <span class="sc">*</span> opportunity <span class="sc">+</span> disadvantage <span class="sc">+</span> <span class="fu">I</span>(disadvantage<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> instability <span class="sc">+</span> heterogeneity,</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> neighb_crime)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>neigh_crime_lm_interaction <span class="sc">|&gt;</span> <span class="fu">coef</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              (Intercept)                   control            opportunitylow 
               3.38090353               -0.24097813               -1.25693555 
        opportunitymedium              disadvantage         I(disadvantage^2) 
              -0.88860860                0.11853371               -0.06206243 
              instability             heterogeneity    control:opportunitylow 
              -0.03271152                0.02178097               -0.36352760 
control:opportunitymedium 
              -0.19551652 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>neigh_crime_lm_interaction <span class="sc">|&gt;</span> <span class="fu">tidy</span>() <span class="sc">|&gt;</span> <span class="fu">select</span>(term, estimate, std.error, p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   term                      estimate std.error   p.value
   &lt;chr&gt;                        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 (Intercept)                 3.38      0.0695 1.84e-153
 2 control                    -0.241     0.0619 1.20e-  4
 3 opportunitylow             -1.26      0.0815 6.95e- 41
 4 opportunitymedium          -0.889     0.0761 1.19e- 26
 5 disadvantage                0.119     0.0291 5.76e-  5
 6 I(disadvantage^2)          -0.0621    0.0168 2.58e-  4
 7 instability                -0.0327    0.0259 2.08e-  1
 8 heterogeneity               0.0218    0.0251 3.86e-  1
 9 control:opportunitylow     -0.364     0.0742 1.52e-  6
10 control:opportunitymedium  -0.196     0.0737 8.39e-  3</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Does the model with the interaction term fit better than the one without? Use a statistical test to compare them and interpret the results of the test.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare models using ANOVA</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(neigh_crime_lm_log, neigh_crime_lm_log2, neigh_crime_lm_interaction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: robbery_log ~ control + opportunity + disadvantage + instability + 
    heterogeneity
Model 2: robbery_log ~ control + opportunity + disadvantage + I(disadvantage^2) + 
    instability + heterogeneity
Model 3: robbery_log ~ control * opportunity + disadvantage + I(disadvantage^2) + 
    instability + heterogeneity
  Res.Df    RSS Df Sum of Sq     F    Pr(&gt;F)    
1    336 72.806                                 
2    335 68.411  1    4.3946 23.02 2.424e-06 ***
3    333 63.570  2    4.8411 12.68 4.931e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Answer:</strong> There is statistical evidence that the model with the interaction term fits better than the one without it because the RSS (residual sum of squares) decreases (68.4 to 63.6) and the p value is even lower and statistically significant (p &lt; 0.001).</p>
</section>
<section id="interpretation-1" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-1">Interpretation</h2>
<blockquote class="blockquote">
<p>This is a complex model—it has a logged outcome and an interaction. Rather than interpreting the coefficients numerically, explain them intuitively. Specifically, at what level of <code>opportunity</code> does <code>control</code> have the strongest association with the log of <code>robbery</code>, and at what level of <code>opportunity</code> does <code>control</code> have the weakest association with the log of <code>robbery</code>?</p>
</blockquote>
<p><strong>Answer:</strong> <code>Control</code> has the strongest association with the log of <code>robbery</code> in neighborhoods with <code>low opportunity.</code> The direction of the effect is negative, meaning that increasing <code>control</code> will reduce <code>robbery</code>, especially in neighborhoods with <code>low opportunity.</code> <code>Control</code> has the weakest association with the log of <code>robbery</code> in neighborhoods with <code>high opportunity,</code> and the direction of the effect is also negative, meaning that increasing <code>control</code> will reduce <code>robbery</code> though to a lesser degree than in neighborhoods with <code>low</code> or <code>medium opportunity.</code></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>